### ISSUE TITLE
容易卡死

### ISSUE THREAD

**Issue by Zheisbug** [0xcrAne/Getcert#1]
当目标有上万个时，会一直卡死。

并且有个小bug
`1:20:57 › python3 getcert.py -f 1.txt         
Traceback (most recent call last):
  File "getcert.py", line 55, in <module>
    f.write(host + ":" + issuedDic['issued_to'] + "\n")
TypeError: can only concatenate str (not "NoneType") to str`
～

**Comment by 0xcrAne** [comment]
上万个目标也不至于内存泄露，是因为在服务器上的跑的内存比较小吗
还有这个bug怎么复现的，你读取的内容能不能发一下

**Comment by Zheisbug** [comment]
内存问题不太确定，2g，4g都试过会卡。

目标是这个 101.37.178.3
-f就会触发 

目前找到httpx替代了这个脚本功能，作者可以参考调用一下。

https://github.com/projectdiscovery/httpx

`echo 'https://github.com/' | ./httpx -tls-probe -json -silent | jq -r '.["tls-grab"]'.dns_names`

**Comment by 0xcrAne** [comment]
不知道这种卡是什么意思，理论上才一万行不会出现内存问题，可能是网络问题，我加了超时机制，可以运行快一点，不知道能不能解决。
这个bug是因为这个ip获取不到值返回了None，将输出格式化后解决。
这个httpx我知道，我是看他这个功能太多了用起来麻烦，自己写了个简单的方便一点
